### ISSUE TITLE
warm_up_wt

### ISSUE THREAD

**Issue by pmzgwu** [MASILab/Augmented-Reality-Programming-Challenge-Walkthrough#3]
![unity_wt1](https://user-images.githubusercontent.com/39998983/96723925-cd834b80-1374-11eb-9b24-b45f20d2f84b.PNG)

**Comment by pmzgwu** [comment]
![unity_wt2](https://user-images.githubusercontent.com/39998983/96725391-72eaef00-1376-11eb-9cc6-c813a2e648f6.PNG)

**Comment by pmzgwu** [comment]
![unity_wt4](https://user-images.githubusercontent.com/39998983/96729646-fe667f00-137a-11eb-9ad0-8bb66fe3f9db.PNG)

**Comment by pmzgwu** [comment]
![unity_wt5](https://user-images.githubusercontent.com/39998983/96730080-746ae600-137b-11eb-8fd3-98e041ae5820.PNG)

**Comment by pmzgwu** [comment]
![unity_wt6](https://user-images.githubusercontent.com/39998983/96731249-a92b6d00-137c-11eb-9988-55055cccc037.PNG)

**Comment by pmzgwu** [comment]
![unity_wt7](https://user-images.githubusercontent.com/39998983/96733226-d2e59380-137e-11eb-9f04-d95f26c25b51.PNG)

**Comment by pmzgwu** [comment]
<img width="557" alt="Screen Shot 2020-10-21 at 9 27 39 AM" src="https://user-images.githubusercontent.com/39998983/96734009-b3029f80-137f-11eb-8dd7-6127334e41a1.png">

**Comment by pmzgwu** [comment]
![unity_wt8](https://user-images.githubusercontent.com/39998983/96742994-1fce6780-1389-11eb-903f-47533f1f7f1a.PNG)

**Comment by pmzgwu** [comment]
![unity_wtss1](https://user-images.githubusercontent.com/39998983/96744453-ab94c380-138a-11eb-96ed-7b41fde3d949.png)

**Comment by pmzgwu** [comment]
![vs_tutorial1](https://user-images.githubusercontent.com/39998983/96749209-23b1b800-1390-11eb-90b0-17c8aae01217.PNG)

**Comment by pmzgwu** [comment]
![vs_tutorial2](https://user-images.githubusercontent.com/39998983/97363380-7ac3fb00-1870-11eb-967e-760c577b8b76.PNG)

**Comment by pmzgwu** [comment]
![vs_tutorial2](https://user-images.githubusercontent.com/39998983/97363655-e908bd80-1870-11eb-8a1d-a7b1e053f202.PNG)

**Comment by pmzgwu** [comment]
![vs_tutorial3](https://user-images.githubusercontent.com/39998983/97363671-f160f880-1870-11eb-8b78-ddc390712a89.PNG)

**Comment by pmzgwu** [comment]
![vs_tutorial4](https://user-images.githubusercontent.com/39998983/97390291-6dc3fd80-18aa-11eb-8e4f-e0e1c2df6b2d.PNG)

**Comment by pmzgwu** [comment]
![vs_tutorial5](https://user-images.githubusercontent.com/39998983/97391563-7a962080-18ad-11eb-8ccc-385a2e28431a.PNG)

**Comment by pmzgwu** [comment]
![unity_wt18](https://user-images.githubusercontent.com/39998983/97394988-f85c2b00-18b1-11eb-95aa-08472480e613.PNG)

**Comment by pmzgwu** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/39998983/97395466-052d4e80-18b3-11eb-93fa-23a293e10fdb.png)

**Comment by pmzgwu** [comment]
<img width="928" alt="BeforeAfterRender" src="https://user-images.githubusercontent.com/39998983/97395938-0f038180-18b4-11eb-9187-9167b7a000be.png">

**Comment by SkylarLNH** [comment]
![1451605065342_ pic_hd](https://user-images.githubusercontent.com/51566827/98843197-97258180-2485-11eb-9b08-3b2d39e9ce59.jpg)

**Comment by SkylarLNH** [comment]
![Uploading 1511605190836_.pic_hd.jpg…]()

**Comment by SkylarLNH** [comment]
![Uploading 1501605190835_.pic_hd.jpg…]()

**Comment by SkylarLNH** [comment]
![1491605190580_ pic_hd](https://user-images.githubusercontent.com/51566827/98952977-0effb480-2537-11eb-97dd-ae871e8b9676.jpg)

**Comment by SkylarLNH** [comment]
![1501605190835_ pic_hd](https://user-images.githubusercontent.com/51566827/98953117-3b1b3580-2537-11eb-8215-598ca43de380.jpg)
